version: '3.1'

services:

  db:
    image: neo4j
    container_name: neo4-container
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "./neodata:/data"
    environment:
      NEO4J_AUTH: none
