version: '3.1'

services:

  neo:
    image: neo4j
    container_name: neo4-container
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "./data:/data"
      - "./import:${NEO4J_HOME}/import"
    environment:
      NEO4J_AUTH: none
